/*     */ package WEB-INF.classes.com.dreammirae.mmth.db.upgrade;
/*     */ 
/*     */ import com.dreammirae.mmth.db.DatabaseAccess;
/*     */ import com.dreammirae.mmth.db.upgrade.DBUpgrade;
/*     */ import java.util.HashMap;
/*     */ import java.util.Map;
/*     */ 
/*     */ 
/*     */ public class Upgrade2_0_0
/*     */   extends DBUpgrade
/*     */ {
/*     */   protected void upgrade() throws Exception {
/*  13 */     Map<DatabaseAccess.DatabaseType, String[]> scripts = (Map)new HashMap<>(3);
/*  14 */     scripts.put(DatabaseAccess.DatabaseType.HSQL, hsqlScript_prev);
/*  15 */     scripts.put(DatabaseAccess.DatabaseType.PGSQL, pgsqlScript_prev);
/*  16 */     scripts.put(DatabaseAccess.DatabaseType.ORACLE, oracleScript_prev);
/*     */     
/*  18 */     runScript(scripts);
/*  19 */     scripts.clear();
/*     */ 
/*     */     
/*  22 */     this.ejt.update("INSERT INTO MMTH_AuthManager (userId, userDeviceId, authType, authFailCnt, totSuccessCnt, tsLastAuth, tsLastAuthFail) SELECT a.userId, da.userDeviceId, da.authType, a.authFailCnt, a.totSuccessCnt, a.tsLastAuth, a.tsLastAuthFail FROM MMTH_AuthManager_copy a left join MMTH_DeviceAppAgents da on da.userDeviceId = a.userDeviceId");
/*     */     
/*  24 */     scripts.put(DatabaseAccess.DatabaseType.HSQL, hsqlScript_post);
/*  25 */     scripts.put(DatabaseAccess.DatabaseType.PGSQL, pgsqlScript_post);
/*  26 */     scripts.put(DatabaseAccess.DatabaseType.ORACLE, oracleScript_post);
/*  27 */     runScript(scripts);
/*     */   }
/*     */ 
/*     */   
/*     */   protected String getNewSchemaVersion() {
/*  32 */     return "2.0.1";
/*     */   }
/*     */   
/*  35 */   private static String[] hsqlScript_prev = new String[] { "DROP TABLE MMTH_IssueCodeData IF EXISTS CASCADE;", "CREATE TABLE MMTH_IssueCodeData (\t id int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),     username VARCHAR(128) NOT NULL,     authType INT NOT NULL,     issueCodeData VARCHAR(128) NOT NULL,     tsLifeTime BIGINT NOT NULL );", "ALTER TABLE MMTH_IssueCodeData ADD CONSTRAINT MMTH_IssueCodeData_Pk PRIMARY KEY (id);", "ALTER TABLE MMTH_IssueCodeData ADD CONSTRAINT MMTH_IssueCodeData_Un1 UNIQUE (username, authType);", "ALTER TABLE MMTH_IssueCodeData ADD FOREIGN KEY (username) REFERENCES MMTH_Users(username) ON DELETE CASCADE;", "ALTER TABLE MMTH_AuthManager RENAME TO MMTH_AuthManager_copy;", "CREATE TABLE MMTH_AuthManager (\t id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),    userId INT NOT NULL,     userDeviceId INT NOT NULL,     authType INT NOT NULL,     authFailCnt INT NOT NULL,     totSuccessCnt INT NOT NULL,     tsLastAuth BIGINT NOT NULL,     tsLastAuthFail BIGINT NOT NULL, );" };
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*  67 */   private static String[] pgsqlScript_prev = new String[] { "DROP TABLE MMTH_IssueCodeData CASCADE;", "DROP SEQUENCE MMTH_IssueCodeData_id_Seq1;", "CREATE SEQUENCE MMTH_IssueCodeData_id_Seq1 INCREMENT BY 1 START WITH 1;", "CREATE TABLE MMTH_IssueCodeData ( \tid INT NOT NULL DEFAULT NEXTVAL('MMTH_IssueCodeData_id_Seq1'),     username VARCHAR(128) NOT NULL,    authType INT NOT NULL,    issueCodeData VARCHAR(128) NOT NULL,    tsLifeTime BIGINT NOT NULL );", "ALTER TABLE MMTH_IssueCodeData ADD CONSTRAINT MMTH_IssueCodeData_Pk PRIMARY KEY (id);", "ALTER TABLE MMTH_IssueCodeData ADD CONSTRAINT MMTH_IssueCodeData_Un1 UNIQUE (username, authType); ", "ALTER TABLE MMTH_IssueCodeData ADD FOREIGN KEY (username) REFERENCES MMTH_Users(username) ON DELETE CASCADE;", "ALTER TABLE MMTH_AuthManager RENAME TO MMTH_AuthManager_copy;", "DROP SEQUENCE MMTH_AuthManager_id_Seq1;", "CREATE SEQUENCE MMTH_AuthManager_id_Seq1 INCREMENT BY 1 START WITH 1;", "CREATE TABLE MMTH_AuthManager ( \tid INT NOT NULL DEFAULT NEXTVAL('MMTH_AuthManager_id_Seq1'),     userId INT NOT NULL,     userDeviceId INT NOT NULL,     authType INT NOT NULL,     authFailCnt INT NOT NULL,     totSuccessCnt INT NOT NULL,     tsLastAuth BIGINT NOT NULL,     tsLastAuthFail BIGINT NOT NULL, );" };
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/* 107 */   private static String[] oracleScript_prev = new String[] { "DROP TRIGGER MMTH_IssueCodeData_id_Tr1;", "DROP TABLE MMTH_IssueCodeData CASCADE CONSTRAINT PURGE;", "DROP SEQUENCE MMTH_IssueCodeData_id_Seq1;", "CREATE SEQUENCE MMTH_IssueCodeData_id_Seq1 INCREMENT BY 1 START WITH 1;", "CREATE TABLE MMTH_IssueCodeData ( \t id NUMBER(10,0) NOT NULL,     username VARCHAR2(128) NOT NULL,     authType NUMBER(10,0) NOT NULL,     issueCodeData VARCHAR2(128) NOT NULL,     tsLifeTime NUMBER(19,0) NOT NULL);", "ALTER TABLE MMTH_IssueCodeData ADD CONSTRAINT MMTH_IssueCodeData_Pk PRIMARY KEY (id);", "ALTER TABLE MMTH_IssueCodeData ADD CONSTRAINT MMTH_IssueCodeData_Un1 UNIQUE (username, authType);", "ALTER TABLE MMTH_IssueCodeData ADD FOREIGN KEY (username) REFERENCES MMTH_Users(username) ON DELETE CASCADE;", "CREATE OR REPLACE TRIGGER MMTH_IssueCodeData_id_Tr1", "BEFORE INSERT ON MMTH_IssueCodeData ", "REFERENCING NEW AS NEW FOR EACH ROW ", "BEGIN ", "    SELECT MMTH_IssueCodeData_id_Seq1.NEXTVAL ", "    INTO :NEW.id ", "    FROM DUAL; ", "END;", "DROP TRIGGER MMTH_AuthManager_id_Tr1;", "ALTER TABLE MMTH_AuthManager RENAME TO MMTH_AuthManager_copy;", "DROP SEQUENCE MMTH_AuthManager_id_Seq1;", "CREATE SEQUENCE MMTH_AuthManager_id_Seq1 INCREMENT BY 1 START WITH 1;", "CREATE TABLE MMTH_AuthManager (\tid NUMBER(10,0) NOT NULL,    userId NUMBER(10,0) NOT NULL,    userDeviceId NUMBER(10,0) NOT NULL,     authType NUMBER(10,0) NOT NULL,    authFailCnt NUMBER(10,0) NOT NULL,    totSuccessCnt NUMBER(10,0) NOT NULL,    tsLastAuth NUMBER(19,0) NOT NULL,    tsLastAuthFail NUMBER(19,0) NOT NULL );", "CREATE OR REPLACE TRIGGER MMTH_AuthManager_id_Tr1", "BEFORE INSERT ON MMTH_AuthManager ", "REFERENCING NEW AS NEW FOR EACH ROW ", "BEGIN ", "    SELECT MMTH_AuthManager_id_Seq1.NEXTVAL ", "    INTO :NEW.id ", "    FROM DUAL; ", "END;" };
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/* 170 */   private static String[] hsqlScript_post = new String[] { "DROP TABLE MMTH_AuthManager_copy IF EXISTS CASCADE;", "ALTER TABLE MMTH_AuthManager ADD CONSTRAINT MMTH_AuthManager_Pk PRIMARY KEY (id);", "ALTER TABLE MMTH_AuthManager ADD CONSTRAINT MMTH_AuthManager_Un1 UNIQUE (userDeviceId, authType);", "ALTER TABLE MMTH_AuthManager ADD FOREIGN KEY (userDeviceId) REFERENCES MMTH_UserDevices(id) ON DELETE CASCADE;" };
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/* 178 */   private static String[] pgsqlScript_post = new String[] { "DROP TABLE MMTH_AuthManager_copy CASCADE;", "ALTER TABLE MMTH_AuthManager ADD CONSTRAINT MMTH_AuthManager_Pk PRIMARY KEY (id);", "ALTER TABLE MMTH_AuthManager ADD CONSTRAINT MMTH_AuthManager_Un1 UNIQUE (userDeviceId, authType);", "ALTER TABLE MMTH_AuthManager ADD FOREIGN KEY (userDeviceId) REFERENCES MMTH_UserDevices(id) ON DELETE CASCADE;" };
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/* 185 */   private static String[] oracleScript_post = new String[] { "DROP TABLE MMTH_AuthManager_copy CASCADE CONSTRAINT PURGE;", "ALTER TABLE MMTH_AuthManager ADD CONSTRAINT MMTH_AuthManager_Pk PRIMARY KEY (id);", "ALTER TABLE MMTH_AuthManager ADD CONSTRAINT MMTH_AuthManager_Un1 UNIQUE (userDeviceId, authType);", "ALTER TABLE MMTH_AuthManager ADD FOREIGN KEY (userDeviceId) REFERENCES MMTH_UserDevices(id) ON DELETE CASCADE;" };
/*     */ }


/* Location:              D:\Authenticator\Authenticator-main\ROOT.jar!\WEB-INF\classes\com\dreammirae\mmth\d\\upgrade\Upgrade2_0_0.class
 * Java compiler version: 7 (51.0)
 * JD-Core Version:       1.1.3
 */