/*     */ package WEB-INF.classes.com.dreammirae.mmth.db.upgrade;
/*     */ 
/*     */ import com.dreammirae.mmth.db.DatabaseAccess;
/*     */ import com.dreammirae.mmth.db.upgrade.DBUpgrade;
/*     */ import java.util.HashMap;
/*     */ import java.util.Map;
/*     */ 
/*     */ 
/*     */ 
/*     */ public class Upgrade2_0_6
/*     */   extends DBUpgrade
/*     */ {
/*     */   protected void upgrade() throws Exception {
/*  14 */     Map<DatabaseAccess.DatabaseType, String[]> scripts = (Map)new HashMap<>(3);
/*  15 */     scripts.put(DatabaseAccess.DatabaseType.HSQL, hsqlScripts);
/*  16 */     scripts.put(DatabaseAccess.DatabaseType.PGSQL, pgsqlScripts);
/*  17 */     scripts.put(DatabaseAccess.DatabaseType.ORACLE, oracleScripts);
/*  18 */     scripts.put(DatabaseAccess.DatabaseType.MYSQL, mysqlScripts);
/*  19 */     scripts.put(DatabaseAccess.DatabaseType.TIBERO, tiberoScripts);
/*     */     
/*  21 */     runScript(scripts);
/*     */   }
/*     */ 
/*     */   
/*     */   protected String getNewSchemaVersion() {
/*  26 */     return "2.0.7";
/*     */   }
/*     */   
/*  29 */   private static String[] hsqlScripts = new String[] { "DROP TABLE MMTH_UserServerPins IF EXISTS CASCADE;", "CREATE TABLE MMTH_UserServerPwd ( \t id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),     userId INT NOT NULL,     pwdType CHAR(1) NOT NULL,     serverPwd VARCHAR(128) NOT NULL,     failCnt INT DEFAULT 0 NOT NULL,     tsReg BIGINT NOT NULL,     tsUpdated BIGINT DEFAULT 0 NOT NULL,     tsLatestFailed BIGINT DEFAULT 0 NOT NULL,     tsExpired BIGINT DEFAULT 0 NOT NULL,     data BLOB NOT NULL  );", "ALTER TABLE MMTH_UserServerPwd ADD CONSTRAINT MMTH_UserServerPwd_Pk PRIMARY KEY (id);", "ALTER TABLE MMTH_UserServerPwd ADD CONSTRAINT MMTH_UserServerPwd_Un1 UNIQUE (userId, pwdType);", "ALTER TABLE MMTH_UserServerPwd ADD CONSTRAINT MMTH_UserServerPwd_Fk1 FOREIGN KEY (userId) REFERENCES MMTH_Users(id) ON DELETE CASCADE;" };
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*  48 */   private static String[] pgsqlScripts = new String[] { "DROP TABLE MMTH_UserServerPins CASCADE;", "DROP SEQUENCE MMTH_UserServerPins_id_Seq1;", "CREATE SEQUENCE MMTH_UserServerPwd_id_Seq1 INCREMENT BY 1 START WITH 1;", "CREATE TABLE MMTH_UserServerPwd (\t \t  id INT NOT NULL DEFAULT NEXTVAL('MMTH_UserServerPwd_id_Seq1'),      userId INT NOT NULL,      pwdType CHAR(1) NOT NULL,      serverPin VARCHAR(128) NOT NULL,      failCnt INT DEFAULT 0 NOT NULL,      tsReg BIGINT NOT NULL,      tsUpdated BIGINT DEFAULT 0 NOT NULL,      tsLatestFailed BIGINT DEFAULT 0 NOT NULL,      tsExpired BIGINT DEFAULT 0 NOT NULL,      data BYTEA NOT NULL );", "ALTER TABLE MMTH_UserServerPwd ADD CONSTRAINT MMTH_UserServerPwd_Pk PRIMARY KEY (id);", "ALTER TABLE MMTH_UserServerPwd ADD CONSTRAINT MMTH_UserServerPwd_Un1 UNIQUE (userId, pwdType);", "ALTER TABLE MMTH_UserServerPwd ADD CONSTRAINT MMTH_UserServerPwd_Fk1 FOREIGN KEY (userId) REFERENCES MMTH_Users(id) ON DELETE CASCADE;" };
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*  69 */   private static String[] oracleScripts = new String[] { "DROP TRIGGER MMTH_UserServerPins_id_Tr1;", "DROP TABLE MMTH_UserServerPins cascade constraints purge;", "DROP SEQUENCE MMTH_UserServerPins_id_Seq1;", "CREATE SEQUENCE MMTH_UserServerPwd_id_Seq1 INCREMENT BY 1 START WITH 1;", "CREATE TABLE MMTH_UserServerPwd ( \t id NUMBER(10,0) NOT NULL,     userId NUMBER(10,0) NOT NULL,     pwdType CHAR(1) NOT NULL,     serverPwd VARCHAR2(128) NOT NULL,     failCnt NUMBER(10,0) DEFAULT 0 NOT NULL,     tsReg NUMBER(19,0) NOT NULL,     tsUpdated NUMBER(19,0) DEFAULT 0 NOT NULL,     tsLatestFailed NUMBER(19,0) DEFAULT 0 NOT NULL,     tsExpired NUMBER(19,0) DEFAULT 0 NOT NULL,     data BLOB NOT NULL );", "ALTER TABLE MMTH_UserServerPwd ADD CONSTRAINT MMTH_UserServerPwd_Pk PRIMARY KEY (id);", "ALTER TABLE MMTH_UserServerPwd ADD CONSTRAINT MMTH_UserServerPwd_Un1 UNIQUE (userId, pwdType);", "CREATE OR REPLACE TRIGGER MMTH_UserServerPwd_id_Tr1BEFORE INSERT ON MMTH_UserServerPwd REFERENCING NEW AS NEW FOR EACH ROW BEGIN     SELECT MMTH_UserServerPwd_id_Seq1.NEXTVAL     INTO :NEW.id     FROM DUAL; END;", "ALTER TABLE MMTH_UserServerPwd ADD CONSTRAINT MMTH_UserServerPwd_Fk1 FOREIGN KEY (userId) REFERENCES MMTH_Users(id) ON DELETE CASCADE;" };
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*  99 */   private static String[] mysqlScripts = new String[] { "DROP TABLE MMTH_UserServerPins CASCADE;", "CREATE TABLE MMTH_UserServerPwd (\t\tid INT NOT NULL AUTO_INCREMENT,     userId INT NOT NULL,     pwdType CHAR(1) NOT NULL,     serverPwd VARCHAR(128) NOT NULL,     failCnt INT DEFAULT 0 NOT NULL,     tsReg BIGINT NOT NULL,     tsUpdated BIGINT DEFAULT 0 NOT NULL,      tsLatestFailed BIGINT DEFAULT 0 NOT NULL,     tsExpired BIGINT DEFAULT 0 NOT NULL,     data LONGBLOB NOT NULL,     PRIMARY KEY (id)) engine=InnoDB;", "ALTER TABLE MMTH_UserServerPwd ADD CONSTRAINT MMTH_UserServerPwd_Un1 UNIQUE (userId, pwdType);", "ALTER TABLE MMTH_UserServerPwd ADD CONSTRAINT MMTH_UserServerPwd_Fk1 FOREIGN KEY (userId) REFERENCES MMTH_Users(id) ON DELETE CASCADE;" };
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/* 118 */   private static String[] tiberoScripts = new String[] { "DROP TRIGGER MMTH_UserServerPins_id_Tr1;", "DROP TABLE MMTH_UserServerPins cascade constraints purge;", "DROP SEQUENCE MMTH_UserServerPins_id_Seq1;", "CREATE SEQUENCE MMTH_UserServerPwd_id_Seq1 INCREMENT BY 1 START WITH 1;", "CREATE TABLE MMTH_UserServerPwd ( \t id NUMBER(10,0) NOT NULL,     userId NUMBER(10,0) NOT NULL,     pwdType CHAR(1) NOT NULL,     serverPwd VARCHAR2(128) NOT NULL,     failCnt NUMBER(10,0) DEFAULT 0 NOT NULL,     tsReg NUMBER(19,0) NOT NULL,     tsUpdated NUMBER(19,0) DEFAULT 0 NOT NULL,     tsLatestFailed NUMBER(19,0) DEFAULT 0 NOT NULL,     tsExpired NUMBER(19,0) DEFAULT 0 NOT NULL,     data BLOB NOT NULL );", "ALTER TABLE MMTH_UserServerPwd ADD CONSTRAINT MMTH_UserServerPwd_Pk PRIMARY KEY (id);", "ALTER TABLE MMTH_UserServerPwd ADD CONSTRAINT MMTH_UserServerPwd_Un1 UNIQUE (userId, pwdType);", "CREATE OR REPLACE TRIGGER MMTH_UserServerPwd_id_Tr1BEFORE INSERT ON MMTH_UserServerPwd REFERENCING NEW AS NEW FOR EACH ROW BEGIN     SELECT MMTH_UserServerPwd_id_Seq1.NEXTVAL     INTO :NEW.id     FROM DUAL; END;", "ALTER TABLE MMTH_UserServerPwd ADD CONSTRAINT MMTH_UserServerPwd_Fk1 FOREIGN KEY (userId) REFERENCES MMTH_Users(id) ON DELETE CASCADE;" };
/*     */ }


/* Location:              D:\Authenticator\Authenticator-main\ROOT.jar!\WEB-INF\classes\com\dreammirae\mmth\d\\upgrade\Upgrade2_0_6.class
 * Java compiler version: 7 (51.0)
 * JD-Core Version:       1.1.3
 */